"""
Report Generator — Produces plain-English fairness audit reports.

Uses Google Gemini (Vertex AI) when available, falls back to a
structured template-based report when API key is not configured.
"""

import os
from typing import Any


class ReportGenerator:
    """Generates audit reports using Gemini or a fallback template."""

    def __init__(self):
        self.api_key = os.getenv("GOOGLE_API_KEY")

    def generate(self, audit_result: dict[str, Any]) -> str:
        """Generate a human-readable fairness audit report."""
        if self.api_key:
            return self._generate_with_gemini(audit_result)
        return self._generate_fallback(audit_result)

    def _generate_with_gemini(self, result: dict[str, Any]) -> str:
        """Call Google Gemini API for AI-powered report."""
        try:
            import google.generativeai as genai

            genai.configure(api_key=self.api_key)
            
            # Try Gemma 4 first, fallback to Gemini 2.5 Flash
            try:
                model = genai.GenerativeModel("gemma-4-27b-it")
            except Exception:
                model = genai.GenerativeModel("gemini-2.5-flash")

            prompt = self._build_prompt(result)
            response = model.generate_content(prompt)
            return response.text
        except Exception as e:
            return self._generate_fallback(result) + f"\n\n[Gemini unavailable: {e}]"

    def _build_prompt(self, result: dict[str, Any]) -> str:
        metrics = result.get("metrics", {})
        score = result.get("fairness_score", 0)
        risk = result.get("risk_level", "unknown")

        return f"""You are a fairness auditor. Generate a professional bias audit report.

Dataset: {result.get('dataset_id', 'Unknown')}
Sensitive Attributes: {result.get('sensitive_attrs', [])}
Fairness Score: {score}/100
Risk Level: {risk}

Metrics:
- Disparate Impact: {metrics.get('disparate_impact', 'N/A')} (threshold: ≥ 0.80)
- Demographic Parity Gap: {metrics.get('demographic_parity_diff', 'N/A')} (threshold: ≤ 0.05)
- Equalized Odds Diff: {metrics.get('equalized_odds_diff', 'N/A')} (threshold: ≤ 0.10)
- Model Accuracy: {metrics.get('model_accuracy', 'N/A')}

Flags: {result.get('flags', [])}

Write sections: Executive Summary, Key Findings, Risk Assessment,
Compliance Notes (EU AI Act, EEOC, ECOA), and Recommended Actions.
Use clear, non-technical language suitable for executives and regulators."""

    def _generate_fallback(self, result: dict[str, Any]) -> str:
        """Template-based report when Gemini is unavailable."""
        metrics = result.get("metrics", {})
        score = result.get("fairness_score", 0)
        risk = result.get("risk_level", "unknown")
        flags = result.get("flags", [])
        di = metrics.get("disparate_impact", 0)
        dp = metrics.get("demographic_parity_diff", 0)
        eo = metrics.get("equalized_odds_diff", 0)
        acc = metrics.get("model_accuracy", 0)

        violations = [f for f in flags if f.get("severity") == "critical"]

        report = f"""═══════════════════════════════════════════════
  FAIRSIGHT — AI FAIRNESS AUDIT REPORT
═══════════════════════════════════════════════

EXECUTIVE SUMMARY
─────────────────
Dataset: {result.get('dataset_id', 'Unknown')}
Sensitive Attributes: {', '.join(result.get('sensitive_attrs', []))}
Fairness Score: {score}/100
Risk Level: {risk.upper()}
Critical Violations: {len(violations)}

KEY FINDINGS
────────────
1. Disparate Impact: {di:.3f} {'✅ PASS' if di >= 0.80 else '❌ FAIL (< 0.80)'}
2. Demographic Parity Gap: {dp*100:.1f}% {'✅ PASS' if dp <= 0.05 else '❌ FAIL (> 5%)'}
3. Equalized Odds Diff: {eo*100:.1f}% {'✅ PASS' if eo <= 0.10 else '❌ FAIL (> 10%)'}
4. Model Accuracy: {acc*100:.1f}%

COMPLIANCE STATUS
─────────────────
• EEOC 4/5ths Rule: {'COMPLIANT' if di >= 0.80 else 'NON-COMPLIANT'}
• EU AI Act: {'Review recommended' if risk != 'low' else 'Low risk'}
• ECOA Fair Lending: {'Requires attention' if di < 0.80 else 'Acceptable'}

RECOMMENDED ACTIONS
───────────────────"""

        for flag in flags:
            report += f"\n• [{flag.get('severity', 'info').upper()}] {flag.get('recommendation', '')}"

        if not flags:
            report += "\n• No critical issues detected. Continue monitoring."

        report += "\n\n═══════════════════════════════════════════════"
        report += "\n  Generated by FairSight (Gemini unavailable — template report)"
        report += "\n═══════════════════════════════════════════════"

        return report
