// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAof5tHED0Y7zla2Ffi8k9SH7sSdEedOQw',
    appId: '1:708608892119:web:4dae841922c8f637832492',
    messagingSenderId: '708608892119',
    projectId: 'fairsight-af293',
    authDomain: 'fairsight-af293.firebaseapp.com',
    storageBucket: 'fairsight-af293.firebasestorage.app',
    measurementId: 'G-SF9NVKSS37',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIJXeGPSakpWZHLGL6VYbMpR9I6tjpfJ0',
    appId: '1:708608892119:ios:28a061e886bf881c832492',
    messagingSenderId: '708608892119',
    projectId: 'fairsight-af293',
    storageBucket: 'fairsight-af293.firebasestorage.app',
    iosBundleId: 'com.fairsight.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAof5tHED0Y7zla2Ffi8k9SH7sSdEedOQw',
    appId: '1:708608892119:web:e6400a42b460556e832492',
    messagingSenderId: '708608892119',
    projectId: 'fairsight-af293',
    authDomain: 'fairsight-af293.firebaseapp.com',
    storageBucket: 'fairsight-af293.firebasestorage.app',
    measurementId: 'G-K5ZZPNJGBF',
  );
}
