import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import '../services/audit_service.dart';

class ReportScreen extends StatefulWidget {
  const ReportScreen({super.key});

  @override
  State<ReportScreen> createState() => _ReportScreenState();
}

class _ReportScreenState extends State<ReportScreen> {
  static const _teal = Color(0xFF0D9488);
  static const _darkBg = Color(0xFF0A1628);

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final svc = context.read<AuditService>();
      if (svc.reportContent == null && svc.currentJob != null) {
        svc.generateReport();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final svc = context.watch<AuditService>();

    return Scaffold(
      backgroundColor: const Color(0xFFF8FAFC),
      appBar: AppBar(
        backgroundColor: _darkBg,
        title: const Text(
          'AI Fairness Report',
          style: TextStyle(color: Colors.white),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => context.go('/results'),
        ),
        actions: [
          if (svc.reportContent != null)
            IconButton(
              icon: const Icon(Icons.share, color: Colors.white),
              tooltip: 'Share report',
              onPressed: () {
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Report sharing coming soon')),
                );
              },
            ),
        ],
      ),
      body: _buildBody(svc),
    );
  }

  Widget _buildBody(AuditService svc) {
    // Loading state
    if (svc.loading) {
      return const Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            CircularProgressIndicator(),
            SizedBox(height: 20),
            Text(
              'Generating AI report with Gemini…',
              style: TextStyle(fontSize: 15, color: Color(0xFF64748B)),
            ),
            SizedBox(height: 8),
            Text(
              'Analyzing metrics and producing recommendations',
              style: TextStyle(fontSize: 13, color: Color(0xFF94A3B8)),
            ),
          ],
        ),
      );
    }

    // Error state
    if (svc.error != null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const Icon(Icons.error_outline, size: 48, color: Color(0xFFEF4444)),
              const SizedBox(height: 16),
              Text(
                svc.error!,
                textAlign: TextAlign.center,
                style: const TextStyle(color: Color(0xFFB91C1C)),
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                onPressed: () => svc.generateReport(),
                style: ElevatedButton.styleFrom(backgroundColor: _teal),
                child: const Text('Retry', style: TextStyle(color: Colors.white)),
              ),
            ],
          ),
        ),
      );
    }

    // No report yet
    if (svc.reportContent == null) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(
              Icons.description_outlined,
              size: 64,
              color: Color(0xFFCBD5E1),
            ),
            const SizedBox(height: 16),
            const Text(
              'No report generated yet',
              style: TextStyle(fontSize: 16, color: Color(0xFF64748B)),
            ),
            const SizedBox(height: 20),
            ElevatedButton.icon(
              onPressed: svc.currentJob != null
                  ? () => svc.generateReport()
                  : null,
              icon: const Icon(Icons.auto_awesome),
              label: const Text('Generate with Gemini'),
              style: ElevatedButton.styleFrom(
                backgroundColor: _teal,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(
                  horizontal: 24,
                  vertical: 14,
                ),
              ),
            ),
          ],
        ),
      );
    }

    // Report content — parse sections and render as cards
    final isTemplate = svc.reportContent!.contains('Generated by FairSight');
    final sections = _parseSections(svc.reportContent!);

    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header banner
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: isTemplate
                  ? const Color(0xFFFACC15).withValues(alpha: 0.1)
                  : _teal.withValues(alpha: 0.08),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(
                color: isTemplate
                    ? const Color(0xFFFACC15).withValues(alpha: 0.4)
                    : _teal.withValues(alpha: 0.3),
              ),
            ),
            child: Row(
              children: [
                Icon(
                  isTemplate ? Icons.warning_amber : Icons.auto_awesome,
                  color: isTemplate ? const Color(0xFF854D0E) : _teal,
                  size: 20,
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    isTemplate
                        ? 'Gemini unavailable — Viewing structured template report'
                        : 'Generated by Google Gemini via Vertex AI',
                    style: TextStyle(
                      color: isTemplate ? const Color(0xFF854D0E) : _teal,
                      fontWeight: FontWeight.w600,
                      fontSize: 13,
                    ),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 16),

          // Render each section as a card
          ...sections.map((section) => _buildSectionCard(section)),

          const SizedBox(height: 20),

          // Actions row
          Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: () => context.read<AuditService>().generateReport(),
                  icon: const Icon(Icons.refresh, size: 18),
                  label: const Text('Regenerate'),
                  style: OutlinedButton.styleFrom(
                    side: const BorderSide(color: _teal),
                    foregroundColor: _teal,
                    padding: const EdgeInsets.symmetric(vertical: 12),
                  ),
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: ElevatedButton.icon(
                  onPressed: () => context.go('/results'),
                  icon: const Icon(Icons.arrow_back, size: 18),
                  label: const Text('Back to Results'),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: _teal,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 12),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  /// Parse report text into titled sections
  List<_ReportSection> _parseSections(String report) {
    final sections = <_ReportSection>[];
    final lines = report.split('\n');

    String? currentTitle;
    final buffer = StringBuffer();

    // Section headers are lines that are:
    // 1. Markdown headers (### TITLE)
    // 2. ALL CAPS lines
    // 3. Known keywords (EXECUTIVE, FINDINGS, ROOT CAUSE, COMPLIANCE, ACTIONS)
    final sectionHeaderRegex = RegExp(r'^(?:#+\s*)?([A-Z][A-Z \u2014\u2500—_\-:]+)$');
    // Separator lines (=== or ---)
    final separatorRegex = RegExp(r'^[=\-]{3,}$');

    for (final line in lines) {
      final trimmed = line.trim();

      // Skip separator lines
      if (separatorRegex.hasMatch(trimmed)) continue;
      // Skip empty header lines like "FAIRSIGHT AI FAIRNESS AUDIT REPORT"
      if (trimmed == 'FAIRSIGHT AI FAIRNESS AUDIT REPORT') continue;
      // Skip footer
      if (trimmed.startsWith('Generated by FairSight')) continue;

      // Clean line for checking
      String cleanLine = trimmed.replaceAll(RegExp(r'[#\*]'), '').trim();
      
      bool isHeader = (sectionHeaderRegex.hasMatch(cleanLine) && cleanLine.length > 3) ||
                      (trimmed.startsWith('###') && trimmed.length > 5) ||
                      (trimmed.startsWith('**') && trimmed.endsWith('**') && trimmed.length > 5);

      if (isHeader) {
        // Save previous section
        if (currentTitle != null) {
          sections.add(_ReportSection(currentTitle!, buffer.toString().trim()));
          buffer.clear();
        }
        currentTitle = cleanLine.replaceAll(':', '');
      } else {
        if (currentTitle != null) {
          buffer.writeln(trimmed);
        }
      }
    }

    // Save last section
    if (currentTitle != null && buffer.isNotEmpty) {
      sections.add(_ReportSection(currentTitle!, buffer.toString().trim()));
    }

    return sections;
  }

  Widget _buildSectionCard(_ReportSection section) {
    final icon = _sectionIcon(section.title);
    final color = _sectionColor(section.title);

    return Container(
      margin: const EdgeInsets.only(bottom: 12),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFE2E8F0)),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.03),
            blurRadius: 8,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Section header
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            decoration: BoxDecoration(
              color: color.withValues(alpha: 0.06),
              borderRadius: const BorderRadius.only(
                topLeft: Radius.circular(12),
                topRight: Radius.circular(12),
              ),
            ),
            child: Row(
              children: [
                Icon(icon, size: 18, color: color),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    _formatTitle(section.title),
                    style: TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w700,
                      color: color,
                      letterSpacing: 0.3,
                    ),
                  ),
                ),
              ],
            ),
          ),
          // Section body
          Padding(
            padding: const EdgeInsets.all(16),
            child: _buildSectionBody(section),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionBody(_ReportSection section) {
    // For KEY FINDINGS section, try to render as a table
    if (section.title.contains('KEY FINDINGS') || section.title.contains('FIVE METRICS')) {
      return _buildMetricsTable(section.body);
    }

    // For RECOMMENDED ACTIONS, render first few bullets as cards, then standard text
    if (section.title.contains('RECOMMENDED') || section.title.contains('ACTIONS')) {
      return _buildActionsSection(section.body);
    }

    // For COMPLIANCE STATUS, render as chips
    if (section.title.contains('COMPLIANCE')) {
      return _buildComplianceSection(section.body);
    }

    // For GROUP BASE RATES, render as cards
    if (section.title.contains('GROUP BASE RATES')) {
      return _buildGroupRates(section.body);
    }

    // Default: render as styled text with line-by-line parsing
    return _buildStyledText(section.body);
  }




  Widget _buildMetricsTable(String body) {
    final lines = body.split('\n').where((l) => l.trim().isNotEmpty).toList();
    final rows = <TableRow>[];

    // Header row
    rows.add(
      const TableRow(
        decoration: BoxDecoration(color: Color(0xFFF1F5F9)),
        children: [
          Padding(
            padding: EdgeInsets.all(8),
            child: Text('Metric', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 12)),
          ),
          Padding(
            padding: EdgeInsets.all(8),
            child: Text('Raw', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 12)),
          ),
          Padding(
            padding: EdgeInsets.all(8),
            child: Text('Cond.', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 12)),
          ),
          Padding(
            padding: EdgeInsets.all(8),
            child: Text('Threshold', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 12)),
          ),
          Padding(
            padding: EdgeInsets.all(8),
            child: Text('Status', style: TextStyle(fontWeight: FontWeight.w700, fontSize: 12)),
          ),
        ],
      ),
    );

    for (final line in lines) {
      final trimmed = line.trim();
      if (trimmed.startsWith('Raw') || trimmed.startsWith('Note:') || trimmed.startsWith('When')) {
        continue; // Skip sub-header and note lines
      }
      if (trimmed.contains('---') && trimmed.contains('|')) {
        continue; // Skip markdown separator line
      }

      // Try splitting by pipe (markdown) or by multiple spaces
      List<String> parts;
      if (trimmed.contains('|')) {
        parts = trimmed.split('|')
            .map((p) => p.trim())
            .where((p) => p.isNotEmpty)
            .toList();
      } else {
        parts = trimmed.split(RegExp(r'\s{2,}')).map((p) => p.trim()).toList();
      }

      if (parts.length >= 3) {
        final metric = parts[0].replaceAll(':', '').trim();
        final raw = parts.length > 1 ? parts[1].trim() : '—';
        final conditional = parts.length > 2 ? parts[2].trim() : '—';

        // Separate threshold from PASS/FAIL status
        String threshold = '—';
        String statusText = '';
        if (parts.length > 3) {
          // Find which part is the threshold (contains >= or <=) and which is PASS/FAIL
          for (int i = 3; i < parts.length; i++) {
            final p = parts[i].trim();
            if (p.contains('>=') || p.contains('<=') || p.contains('>') || p.contains('<')) {
              threshold = p;
            } else if (p.contains('PASS') || p.contains('FAIL') || p == '—') {
              statusText += (statusText.isEmpty ? '' : ' ') + p;
            }
          }
        }

        // Determine colors based on raw value failing
        final rawFails = statusText.startsWith('FAIL') || (statusText.contains('FAIL') && !statusText.startsWith('PASS'));
        final rawColor = rawFails ? const Color(0xFFEF4444) : const Color(0xFF10B981);
        final condColor = (conditional == '—' || conditional == 'N/A')
            ? const Color(0xFF94A3B8) 
            : (statusText.endsWith('FAIL') ? const Color(0xFFEF4444) : const Color(0xFF10B981));

        rows.add(
          TableRow(
            children: [
              Padding(
                padding: const EdgeInsets.all(8),
                child: _parseBoldText(metric, fontSize: 12, fontWeight: FontWeight.w500),
              ),
              Padding(
                padding: const EdgeInsets.all(8),
                child: _parseBoldText(raw, fontSize: 12, fontFamily: 'monospace', color: rawFails ? const Color(0xFFEF4444) : const Color(0xFF1E293B)),
              ),
              Padding(
                padding: const EdgeInsets.all(8),
                child: _parseBoldText(conditional, fontSize: 12, fontFamily: 'monospace', color: conditional == '—' ? const Color(0xFF94A3B8) : condColor),
              ),
              Padding(
                padding: const EdgeInsets.all(8),
                child: _parseBoldText(threshold, fontSize: 11, color: const Color(0xFF94A3B8)),
              ),
              Padding(
                padding: const EdgeInsets.all(8),
                child: _buildStatusChips(statusText),
              ),
            ],
          ),
        );
      }
    }

    // Add note at bottom
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Table(
          columnWidths: const {
            0: FlexColumnWidth(2.5),
            1: FlexColumnWidth(1.2),
            2: FlexColumnWidth(1.2),
            3: FlexColumnWidth(1.2),
            4: FlexColumnWidth(1.5),
          },
          border: TableBorder.all(color: const Color(0xFFE2E8F0), width: 0.5),
          children: rows,
        ),
        const SizedBox(height: 8),
        const Text(
          'Conditional metrics account for each group\'s actual qualification rate.',
          style: TextStyle(fontSize: 11, color: Color(0xFF94A3B8), fontStyle: FontStyle.italic),
        ),
      ],
    );
  }

  Widget _buildStatusChips(String status) {
    final chips = <Widget>[];
    for (final part in status.split('/')) {
      final trimmed = part.trim();
      if (trimmed == 'PASS') {
        chips.add(_statusChip('PASS', const Color(0xFF10B981)));
      } else if (trimmed == 'FAIL') {
        chips.add(_statusChip('FAIL', const Color(0xFFEF4444)));
      } else if (trimmed.isNotEmpty && trimmed != '—') {
        chips.add(Text(trimmed, style: const TextStyle(fontSize: 11, color: Color(0xFF94A3B8))));
      }
      if (chips.isNotEmpty && part != status.split('/').last) {
        chips.add(const SizedBox(width: 4));
      }
    }
    return Wrap(spacing: 4, children: chips);
  }

  Widget _statusChip(String label, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.12),
        borderRadius: BorderRadius.circular(4),
      ),
      child: Text(
        label,
        style: TextStyle(fontSize: 10, fontWeight: FontWeight.w700, color: color),
      ),
    );
  }

  Widget _buildComplianceSection(String body) {
    final lines = body.split('\n').where((l) => l.trim().isNotEmpty).toList();
    return Wrap(
      spacing: 8,
      runSpacing: 8,
      children: lines.map((line) {
        // Clean leading markdown bullet points or numbers
        final cleanLine = line.trim().replaceFirst(RegExp(r'^[\-\*\•\d\.\s]+'), '');
        final parts = cleanLine.split(':');
        if (parts.length < 2) return const SizedBox.shrink();
        final label = parts[0].trim();
        final status = parts.sublist(1).join(':').trim().toUpperCase();

        Color color;
        IconData icon;
        if (status == 'COMPLIANT') {
          color = const Color(0xFF10B981);
          icon = Icons.check_circle;
        } else if (status.contains('NON-COMPLIANT')) {
          color = const Color(0xFFEF4444);
          icon = Icons.cancel;
        } else {
          color = const Color(0xFFF59E0B);
          icon = Icons.warning;
        }

        return Container(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
          decoration: BoxDecoration(
            color: color.withValues(alpha: 0.06),
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: color.withValues(alpha: 0.25)),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(icon, size: 14, color: color),
              const SizedBox(width: 6),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(label, style: TextStyle(fontSize: 11, fontWeight: FontWeight.w600, color: color)),
                  _parseBoldText(status, fontSize: 10, color: color.withValues(alpha: 0.8)),
                ],
              ),
            ],
          ),
        );
      }).toList(),
    );
  }

  Widget _buildActionsSection(String body) {
    final lines = body.split('\n');
    bool reachedSubHeader = false;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: lines.map((line) {
        final trimmed = line.trim();
        if (trimmed.isEmpty) return const SizedBox(height: 4);

        // Check for specific severity tags first (these might not have bullet points)
        if (trimmed.startsWith('[CRITICAL]')) {
          return _actionItem(trimmed.replaceFirst('[CRITICAL]', '').trim(), const Color(0xFFEF4444), Icons.error);
        }
        if (trimmed.startsWith('[WARNING]')) {
          return _actionItem(trimmed.replaceFirst('[WARNING]', '').trim(), const Color(0xFFF59E0B), Icons.warning);
        }
        if (trimmed.startsWith('[INFO]')) {
          return _actionItem(trimmed.replaceFirst('[INFO]', '').trim(), const Color(0xFF3B82F6), Icons.info);
        }

        // Sub-headers (e.g., MONITORING (Always):)
        if (trimmed.endsWith(':') || (trimmed.startsWith('**') && trimmed.endsWith('**:'))) {
          reachedSubHeader = true;
          return Padding(
            padding: const EdgeInsets.only(top: 12, bottom: 6),
            child: _parseBoldText(trimmed, fontSize: 12, fontWeight: FontWeight.w700, color: const Color(0xFF475569)),
          );
        }

        // Bullet points
        if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
          final text = trimmed.substring(2).trim();
          
          // Check for tags INSIDE the bullet point
          if (text.startsWith('[CRITICAL]')) return _actionItem(text.replaceFirst('[CRITICAL]', '').trim(), const Color(0xFFEF4444), Icons.error);
          if (text.startsWith('[WARNING]')) return _actionItem(text.replaceFirst('[WARNING]', '').trim(), const Color(0xFFF59E0B), Icons.warning);
          if (text.startsWith('[INFO]')) return _actionItem(text.replaceFirst('[INFO]', '').trim(), const Color(0xFF3B82F6), Icons.info);

          // Promoted actions (before sub-headers) get the warning card
          if (!reachedSubHeader) {
            return _actionItem(text, const Color(0xFFF59E0B), Icons.warning);
          }
          
          // Standard monitoring bullets (after sub-headers)
          return Padding(
            padding: const EdgeInsets.only(left: 8, bottom: 6),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Padding(
                  padding: EdgeInsets.only(top: 6),
                  child: Icon(Icons.chevron_right, size: 14, color: Color(0xFF94A3B8)),
                ),
                const SizedBox(width: 6),
                Expanded(child: _parseBoldText(text, fontSize: 13, color: const Color(0xFF475569))),
              ],
            ),
          );
        }

        return Padding(
          padding: const EdgeInsets.only(bottom: 6),
          child: _parseBoldText(trimmed),
        );
      }).toList(),
    );
  }

  Widget _buildGroupRates(String body) {
    final lines = body.split('\n').where((l) => l.trim().isNotEmpty).toList();
    return Column(
      children: lines.map((line) {
        final isFair = line.contains('Fair');
        final color = isFair ? const Color(0xFF10B981) : const Color(0xFFF59E0B);
        return Container(
          width: double.infinity,
          margin: const EdgeInsets.only(bottom: 8),
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
          decoration: BoxDecoration(
            color: color.withValues(alpha: 0.04),
            borderRadius: BorderRadius.circular(10),
            border: Border.all(color: color.withValues(alpha: 0.15)),
          ),
          child: Text(
            line.trim(),
            style: TextStyle(
              fontSize: 13, 
              color: color.withValues(alpha: 0.7),
              height: 1.4,
              letterSpacing: 0.1,
            ),
          ),
        );
      }).toList(),
    );
  }

  Widget _buildStyledText(String body) {
    final lines = body.split('\n');
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: lines.map((line) {
        final trimmed = line.trim();
        if (trimmed.isEmpty) return const SizedBox(height: 4);

        // Action items with severity markers
        if (trimmed.startsWith('[CRITICAL]')) {
          return _actionItem(trimmed.replaceFirst('[CRITICAL]', '').trim(), const Color(0xFFEF4444), Icons.error);
        }
        if (trimmed.startsWith('[WARNING]')) {
          return _actionItem(trimmed.replaceFirst('[WARNING]', '').trim(), const Color(0xFFF59E0B), Icons.warning);
        }
        if (trimmed.startsWith('[INFO]')) {
          return _actionItem(trimmed.replaceFirst('[INFO]', '').trim(), const Color(0xFF3B82F6), Icons.info);
        }

        // Sub-headers
        if (trimmed.endsWith(':') || (trimmed.startsWith('**') && trimmed.endsWith('**:'))) {
          return Padding(
            padding: const EdgeInsets.only(top: 8, bottom: 4),
            child: _parseBoldText(trimmed, fontSize: 12, fontWeight: FontWeight.w700, color: const Color(0xFF475569)),
          );
        }

        // Normal text
        return Padding(
          padding: const EdgeInsets.only(bottom: 4),
          child: _parseBoldText(trimmed),
        );
      }).toList(),
    );
  }

  Widget _parseBoldText(String text, {
    double fontSize = 13, 
    Color color = const Color(0xFF1E293B),
    FontWeight fontWeight = FontWeight.normal,
    String? fontFamily,
    double height = 1.6,
  }) {
    final spans = <TextSpan>[];
    final regExp = RegExp(r'\*\*(.*?)\*\*');
    int lastMatchEnd = 0;

    for (final match in regExp.allMatches(text)) {
      if (match.start > lastMatchEnd) {
        spans.add(TextSpan(text: text.substring(lastMatchEnd, match.start)));
      }
      spans.add(TextSpan(
        text: match.group(1),
        style: TextStyle(fontWeight: FontWeight.bold, fontSize: fontSize, color: color, fontFamily: fontFamily),
      ));
      lastMatchEnd = match.end;
    }

    if (lastMatchEnd < text.length) {
      spans.add(TextSpan(text: text.substring(lastMatchEnd)));
    }

    if (spans.isEmpty) {
      return Text(
        text,
        style: TextStyle(fontSize: fontSize, color: color, fontWeight: fontWeight, fontFamily: fontFamily, height: height),
      );
    }

    return RichText(
      text: TextSpan(
        style: TextStyle(fontSize: fontSize, color: color, fontWeight: fontWeight, fontFamily: fontFamily, height: height),
        children: spans,
      ),
    );
  }

  Widget _actionItem(String text, Color color, IconData icon) {
    return Container(
      margin: const EdgeInsets.only(bottom: 6),
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.06),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: color.withValues(alpha: 0.2)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, size: 16, color: color),
          const SizedBox(width: 8),
          Expanded(
            child: Text(text, style: TextStyle(fontSize: 12, color: color, height: 1.4)),
          ),
        ],
      ),
    );
  }

  String _formatTitle(String raw) {
    // Convert "KEY FINDINGS — FIVE METRICS" to "Key Findings — Five Metrics"
    return raw.split(' ').map((w) {
      if (w == '—' || w == '-') return w;
      if (w.isEmpty) return w;
      return w[0].toUpperCase() + w.substring(1).toLowerCase();
    }).join(' ');
  }

  IconData _sectionIcon(String title) {
    if (title.contains('EXECUTIVE')) return Icons.summarize;
    if (title.contains('KEY FINDINGS') || title.contains('METRICS')) return Icons.analytics;
    if (title.contains('GROUP')) return Icons.groups;
    if (title.contains('ROOT CAUSE')) return Icons.search;
    if (title.contains('COMPLIANCE')) return Icons.gavel;
    if (title.contains('RECOMMENDED') || title.contains('ACTIONS')) return Icons.lightbulb;
    return Icons.article;
  }

  Color _sectionColor(String title) {
    if (title.contains('EXECUTIVE')) return const Color(0xFF0D9488);
    if (title.contains('KEY FINDINGS') || title.contains('METRICS')) return const Color(0xFF3B82F6);
    if (title.contains('GROUP')) return const Color(0xFF8B5CF6);
    if (title.contains('ROOT CAUSE')) return const Color(0xFFF59E0B);
    if (title.contains('COMPLIANCE')) return const Color(0xFF6366F1);
    if (title.contains('RECOMMENDED') || title.contains('ACTIONS')) return const Color(0xFF10B981);
    return const Color(0xFF64748B);
  }
}

class _ReportSection {
  final String title;
  final String body;
  _ReportSection(this.title, this.body);
}
